name: grapevine-global-tree
channels:
  - bioconda
  - conda-forge
  - defaults
  - cov-ert
  - anaconda
dependencies:
  - biopython=1.74
  - coreutils=8.25
  - iqtree=1.6
  - mafft
  - pip=19.3.1
  - python=3.7.4
  - snakemake-minimal
  - fasttree
  - gotree
  - jclusterfunk
  - r-base=3.5.1
  - r-networkd3
  - cxx-compiler
  - protobuf=3.12
  - cmake=3.10
  - make
  - boost-cpp
  - git
  - wget
  - rsync
  - pip:
      - git+https://github.com/cov-ert/fastafunk.git
      - git+https://github.com/cov-ert/clusterfunk.git
