name: grapevine-global-tree
channels:
  - bioconda
  - conda-forge
  - defaults
  - cov-ert
dependencies:
  - biopython>=1.74
  - mafft
  - pip
  - python>=3.7
  - snakemake-minimal
  - fasttree
  - gotree
  - jclusterfunk
  - ucsc-fatovcf
  - usher
  - pip:
      - git+https://github.com/cov-ert/fastafunk.git
      - git+https://github.com/cov-ert/clusterfunk.git
